baseURL: "lucpaluskiewicz.github.io" 
title: Luc Paluskiewicz
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About Me
          url: aboutme/
          weight: 2
        - name: Research
          url: research/
          weight: 3
        - name: Resume
          url: resume/
          weight: 4
        - name: Teaching
          url: teaching/
          weight: 5
    
params:
    description: "Economics PhD Candidate at Paris School of Economics, Collège de France and EHESS"
    author: Luc Paluskiewicz
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["aboutme", "workingpapers", "workinprogress", "teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Luc Paluskiewicz
          subtitle: "Welcome to my website! I am a PhD candidate in Economics at [Paris School of Economics](https://www.parisschoolofeconomics.eu/), [Collège de France](https://www.college-de-france.fr/fr) and at the [EHESS](https://www.ehess.fr/fr). My research interests are in Innovation Economics and Political Economy. I am supervised by [Philippe Aghion](https://www.philippeaghion.com/).  I hold a Master's degree in Analysis and Policy in Economics from the Paris School of Economics (PSE).
          imageUrl: "photo1.png"
          imageTitle: Luc Paluskiewicz
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: aboutme/
            - name: Research
              url: research/
            - name: Resume
              url: resume/
            - name: Teaching
              url: teaching/

    socialIcons:
        - name: cv
          url: CV_2024.pdf
        - name: Email
          url: mailto:luc.paluskiewicz@psemail.eu
        - name: Bluesky
          url: 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Luc Paluskiewicz"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
